library(renv)
library(here)
library(odbc)
library(tidyverse)
library(janitor)
library(hablar)
library(readxl)
library(arrow)
library(odbc)
library(lubridate)


SMRAConnection <- dbConnect(
  odbc(),
  dsn = "SMRA",
  uid = Sys.info()[["user"]],
  # Assumes the user's SMR01 username is the same as their R server username
  pwd = "keyring::key_get("SMRA", Sys.info()[["user"]], keyring = "DATABASE"))"
)

data_smr01_raw <- as_tibble(dbGetQuery(
  SMRAConnection,
  paste0(
    "SELECT UPI_NUMBER, CI_CHI_NUMBER, LINK_NO, CIS_MARKER, ADMISSION_DATE, DISCHARGE_DATE, SEX, DOB,
    HBTREAT_CURRENTDATE, LOCATION,
    MAIN_CONDITION, OTHER_CONDITION_1,
    OTHER_CONDITION_2, OTHER_CONDITION_3,
    OTHER_CONDITION_4, OTHER_CONDITION_5
    FROM ANALYSIS.SMR01_PI SMR
    WHERE SMR.DISCHARGE_DATE >= TO_DATE('2010-01-01', 'yyyy-mm-dd')
    AND (
      -- Check if any condition column starts with one of the specified codes
      (MAIN_CONDITION LIKE 'E762%' OR MAIN_CONDITION LIKE 'G10%' OR MAIN_CONDITION LIKE 'G310%' OR MAIN_CONDITION LIKE 'G318%' OR MAIN_CONDITION LIKE 'G20%' OR MAIN_CONDITION LIKE 'A810%' OR MAIN_CONDITION LIKE 'G30%' OR MAIN_CONDITION LIKE 'F0%') OR
      (OTHER_CONDITION_1 LIKE 'E762%' OR OTHER_CONDITION_1 LIKE 'G10%' OR OTHER_CONDITION_1 LIKE 'G310%' OR OTHER_CONDITION_1 LIKE 'G318%' OR OTHER_CONDITION_1 LIKE 'G20%' OR OTHER_CONDITION_1 LIKE 'A810%' OR OTHER_CONDITION_1 LIKE 'G30%' OR OTHER_CONDITION_1 LIKE 'F0%') OR
      (OTHER_CONDITION_2 LIKE 'E762%' OR OTHER_CONDITION_2 LIKE 'G10%' OR OTHER_CONDITION_2 LIKE 'G310%' OR OTHER_CONDITION_2 LIKE 'G318%' OR OTHER_CONDITION_2 LIKE 'G20%' OR OTHER_CONDITION_2 LIKE 'A810%' OR OTHER_CONDITION_2 LIKE 'G30%' OR OTHER_CONDITION_2 LIKE 'F0%') OR
      (OTHER_CONDITION_3 LIKE 'E762%' OR OTHER_CONDITION_3 LIKE 'G10%' OR OTHER_CONDITION_3 LIKE 'G310%' OR OTHER_CONDITION_3 LIKE 'G318%' OR OTHER_CONDITION_3 LIKE 'G20%' OR OTHER_CONDITION_3 LIKE 'A810%' OR OTHER_CONDITION_3 LIKE 'G30%' OR OTHER_CONDITION_3 LIKE 'F0%') OR
      (OTHER_CONDITION_4 LIKE 'E762%' OR OTHER_CONDITION_4 LIKE 'G10%' OR OTHER_CONDITION_4 LIKE 'G310%' OR OTHER_CONDITION_4 LIKE 'G318%' OR OTHER_CONDITION_4 LIKE 'G20%' OR OTHER_CONDITION_4 LIKE 'A810%' OR OTHER_CONDITION_4 LIKE 'G30%' OR OTHER_CONDITION_4 LIKE 'F0%') OR
      (OTHER_CONDITION_5 LIKE 'E762%' OR OTHER_CONDITION_5 LIKE 'G10%' OR OTHER_CONDITION_5 LIKE 'G310%' OR OTHER_CONDITION_5 LIKE 'G318%' OR OTHER_CONDITION_5 LIKE 'G20%' OR OTHER_CONDITION_5 LIKE 'A810%' OR OTHER_CONDITION_5 LIKE 'G30%' OR OTHER_CONDITION_5 LIKE 'F0%')
    )
    ORDER BY link_no, admission_date, discharge_date, admission, discharge, uri ASC"
  ))) %>%
  clean_names()

data_smr01 <- data_smr01_raw %>%
  mutate(age_on_admission = floor(lubridate::time_length(interval(dob, admission_date), "year"))) %>%
  filter(age_on_admission < 18)

